title: Life Tips
description: 일상을 바꾸는 꿀팁과 가성비 최고 꿀템 추천.
url: "https://life-tips.enjoy-onepage.com"
baseurl: ''
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
